plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: kramdown

collections:
  manual:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      author: Bndtools.org
      image: /images/swirl-128.png

title: Bndtools

logo: /images/swirl-128.png


exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'
  - 'CONTRIBUTING.md'
  - 'LICENSE'
  - '.travis.yml'
  - '.gitignore'
  - '.project'
  - 'run.sh'
  - '/vendor'

